stages:
  - build

.if-protected: &if-protected
  if: '($CI_COMMIT_BRANCH =~ /^esp_based_on_v/)'

.if-dev-push: &if-dev-push
  if: '$CI_COMMIT_BRANCH !~ /^esp_based_on_v/ && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event")'

.rules:build:examples:
  rules:
    - <<: *if-protected
    - <<: *if-dev-push

.build_template: &build_template
  stage: build
  tags:
    - build
  image: ${IMAGE}
  variables:
    # Enable ccache for all build jobs. See configure_ci_environment.sh for more ccache related settings.
    IDF_CCACHE_ENABLE: "1"
    BATCH_BUILD: "1"
    V: "0"
    WARNING_STR: ""

.build_sdk: &build_sdk |
  export EXTRA_CFLAGS=$EXTRA_CFLAGS
  export EXTRA_CXXFLAGS=$EXTRA_CFLAGS

  if [ "${SDKCONFIG_DEFAULTS}" ]; then
    idf.py -DSDKCONFIG_DEFAULTS="${SDKCONFIG_DEFAULTS}" set-target ${IDF_TARGET}
  else
    idf.py set-target ${IDF_TARGET}
  fi

  idf.py build

.build_examples_template: &build_examples_template
  <<: *build_template
  artifacts:
    when: always
    paths:
      - "**/build*/*.bin"
      # upload to s3 server to save the artifacts size
      - "**/build*/*.map"
      - "**/build*/*.elf"
      - "**/build*/flasher_args.json"
      - "**/build*/flash_project_args"
      - "**/build*/config/sdkconfig.json"
      - "**/build*/bootloader/*.bin"
      - "**/build*/bootloader/*.elf"
      - "**/build*/partition_table/*.bin"
    expire_in: 1 week
  variables:
    IDF_CI_BUILD: "1"
    EXTRA_CFLAGS: "-Werror -Werror=deprecated-declarations"
  script:
    - cd $EXAMPLE_DIR
    - *build_sdk

build_test_esp32:
  extends:
    - .build_examples_template
    - .rules:build:examples
  parallel:
    matrix:
      - IMAGE: [espressif/idf:release-v4.4, espressif/idf:release-v5.0, espressif/idf:release-v5.1, espressif/idf:release-v5.2, espressif/idf:latest]
        IDF_TARGET: [esp32]
  variables:
    EXAMPLE_DIR: product-mini/platforms/esp-idf

build_test_esp32c3:
  extends:
    - .build_examples_template
    - .rules:build:examples
  parallel:
    matrix:
      - IMAGE: [espressif/idf:release-v4.4, espressif/idf:release-v5.0, espressif/idf:release-v5.1, espressif/idf:release-v5.2, espressif/idf:latest]
        IDF_TARGET: [esp32c3]
  variables:
    EXAMPLE_DIR: product-mini/platforms/esp-idf

build_test_esp32c6:
  extends:
    - .build_examples_template
    - .rules:build:examples
  parallel:
    matrix:
      - IMAGE: [espressif/idf:release-v5.1, espressif/idf:release-v5.2, espressif/idf:latest]
        IDF_TARGET: esp32c6
  variables:
    EXAMPLE_DIR: product-mini/platforms/esp-idf

build_test_esp32s3:
  extends:
    - .build_examples_template
    - .rules:build:examples
  parallel:
    matrix:
      - IMAGE: [espressif/idf:release-v4.4, espressif/idf:release-v5.0, espressif/idf:release-v5.1, espressif/idf:release-v5.2, espressif/idf:latest]
        IDF_TARGET: [esp32s3]
        SDKCONFIG_DEFAULTS: sdkconfig.defaults.esp32s3.ci
  variables:
    EXAMPLE_DIR: product-mini/platforms/esp-idf
